 language: node_js
 node_js:
   - "4.2"
   - "4.0"
   - "0.12"
   - "0.10"
 branches:
 only:
  - master
 notifications:
  email:
   - joaquim.serafim@gmail.com
 script: npm test
 before_install:
  - npm install -g npm@~1.4.6
